spring:
  datasource:
    url: jdbc:mysql://43.201.7.138:3306/des_database
    username: root
    password: desroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update                                     # ?????? ??? ???? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true                                         # ???? SQL ?? ?? ?? ??
    properties:
      hibernate:
        format_sql: true                                   # SQL ??? ???? ?? ?? ??
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x? ???? ??, ??? ?? ??
        hibernate.id.new_generator_mappings: true          # ??? ID ?? ?? ?? ??

  logging:
    level:
      org.hibernate.SQL: DEBUG                             # Hibernate SQL ?? ?? ?? ??
      org.hibernate.type.descriptor.sql.BasicTypeRegistry: TRACE # SQL ?? ??? ?? ?? ??

  transaction:
    default-timeout: 30                                   # ?? ???? ???? ?? (? ??)

  springdoc:
    swagger-ui:
      path: /api-test  # swagger-ui ?? ??? ?? ??
      groups-order: DESC # path, query, body, response ??? ??
      tags-sorter: alpha # ??? ??? ??? ??
      operations-sorter: method  # delete - get - patch - post - put ??? ??, alpha? ???? ??? ??? ?? ??
    paths-to-match:
      - /api/**

